### PR TITLE
Created docker container and documentation for quickstarting

### PR DESCRIPTION
**Pull request by warmfusion**
To save the hassle of needing apache and so on, I've created a trivial docker container to make this work.

See the README changes to how it works,

### CODE REVIEW

**Comment by sirloper** [comment]
Love this. Thank you. As soon as I have a few minutes I'll merge this!

**Comment by sirloper** [comment]
After reviewing the code, it appears to change the module to docker-only rather than add the functionality as available.  Is that the case?  if so, I think I'd rather keep the branch separate for those that cannot or do not want to use a docker container, although I think we'll be adopting it ourselves.

**Comment by warmfusion** [comment]
I'm not sure why you think that makes the project docker only?

The only changes to the module that i've made is to ;
1. bind to any interface where before it'd have only bound to lo0 (localhost)
   - This is to expose the application on eth0 and therefore become avaliable through docker's port routing
2. Allow the puppet server endpoint to be configured through ENV property
   - So that we can specify other hosts running puppetdb through the container rather than hardcode
3. Allow the cache expiry time to be defined through ENV property - default remains at 300 seconds
   - As above - So we can override the default through configuration rather than hardcoded
4. Changed the default puppetdb host from 'localhost' to 'puppet' as this is the default name for puppet masters 
   - I can change this back if desired as it appears to be the only 'impacting' change

**Comment by sirloper** [comment]
Thanks for the clarification.  There was one small merge conflict (the 
puppetdb version was still static on your branch) -- that was resolved 
and the pull request was merged.

Thank you for your contribution!!

**Pull request merged**
